### ISSUE TITLE
[Question] Does this action works with private/org repositories?

### ISSUE THREAD

**Issue by codebydant** [ShieldedDotDev/shielded-action#1]
Hi @donatj,

Greetings.

I was wondering if this action can be used in an organization repository to dynamically update a badge readme.

**Comment by donatj** [comment]
So we’re still in pretty early beta. 

What this action does is allows you to set the title/text/color of a badge like this one from within a GitHub action.

![Last Update](https://img.shielded.dev/s/ewh)

You can include the markdown of the badge in your README and it will dynamically update. 

You will need to sign up on https://shielded.dev by clicking the big “Sign in with GitHub” button. That will bring you to the Dashboard.

Once you are in the dashboard, create one or more badges with the big + button. This will give you two important things, the markdown for the badge and its API key to use with the action.

Let me know if you have any questions, as I mentioned we’re in beta and as such I would love any feedback about the process, design, etc.

**Comment by donatj** [comment]
Let me know if you have any questions or anything, otherwise I'm going to close this ticket in a little bit.

**Comment by donatj** [comment]
I'm closing. Feel free to reopen if you have any other questions.
